### ISSUE TITLE
Define a place for questions

### ISSUE THREAD

**Issue by Olezha** [Bombe/fresta#1]
Freenet REST API is a very good idea for a subproject!

I run the project and all works, although I do not know the technology. Just according to the instructions. Super. (I only wants suggest to adding a link to the jFCPlib in the readme)

But my question is: why Kotlin? I look for other languages ​​for the JVM, but have not yet reached the project where I used it. I do not know and I have no arguments, but I'm not sure. It is worth holding such a holywar. Not? But this is your project and I just ask.

I don’t know where to ask something. I think a good place could be a separate board in FMS. Or another place. So I think it’s worth saying in the project readme where to look for communication.

And, of course, many thanks to you.

PS: The code looks beautiful

**Comment by Bombe** [comment]
I’ve been using Kotlin since… don’t know, 2016 or so? I love the way it lets me express the purpose of the code way better than Java, and I also love that I still have the complete Java eco system at my disposal. It’s kind of an easy decision for me. :)

Also, I just created the FMS “fresta” board. Come and join me there! :)
